import { WeekdayName, WeekdayThemeConfig } from '../types';

export const WEEKDAY_THEMES: Record<WeekdayName, WeekdayThemeConfig> = {
  Monday: {
    name: 'Monday',
    colorName: 'White',
    accentColor: '#475569',
    borderClass: 'border-slate-300',
    badgeClass: 'bg-slate-100 text-slate-800 border-slate-300 font-semibold',
    buttonClass: 'bg-slate-800 hover:bg-slate-900 text-white border-slate-700 shadow-sm',
    headerGlowClass: 'from-slate-700 via-slate-800 to-slate-900',
    cardAccentClass: 'border-l-4 border-slate-700',
    textAccentClass: 'text-slate-800',
    subtleBgClass: 'bg-slate-100',
    headerBgClass: 'bg-slate-800',
    cardLeftBorderClass: 'border-slate-700',
  },
  Tuesday: {
    name: 'Tuesday',
    colorName: 'Black',
    accentColor: '#0f172a',
    borderClass: 'border-slate-300',
    badgeClass: 'bg-slate-900 text-slate-100 border-slate-800 font-semibold',
    buttonClass: 'bg-slate-900 hover:bg-black text-white border-slate-800 shadow-sm',
    headerGlowClass: 'from-slate-900 via-slate-950 to-black',
    cardAccentClass: 'border-l-4 border-slate-900',
    textAccentClass: 'text-slate-900',
    subtleBgClass: 'bg-slate-100',
    headerBgClass: 'bg-slate-900',
    cardLeftBorderClass: 'border-slate-900',
  },
  Wednesday: {
    name: 'Wednesday',
    colorName: 'Pink',
    accentColor: '#db2777',
    borderClass: 'border-pink-200',
    badgeClass: 'bg-pink-100 text-pink-700 border-pink-200 font-semibold',
    buttonClass: 'bg-pink-600 hover:bg-pink-700 text-white border-pink-500 shadow-sm',
    headerGlowClass: 'from-pink-600 via-pink-700 to-pink-800',
    cardAccentClass: 'border-l-4 border-pink-600',
    textAccentClass: 'text-pink-600',
    subtleBgClass: 'bg-pink-50',
    headerBgClass: 'bg-pink-600',
    cardLeftBorderClass: 'border-pink-600',
  },
  Thursday: {
    name: 'Thursday',
    colorName: 'Green',
    accentColor: '#059669',
    borderClass: 'border-emerald-200',
    badgeClass: 'bg-emerald-100 text-emerald-700 border-emerald-200 font-semibold',
    buttonClass: 'bg-emerald-600 hover:bg-emerald-700 text-white border-emerald-500 shadow-sm',
    headerGlowClass: 'from-emerald-600 via-emerald-700 to-emerald-800',
    cardAccentClass: 'border-l-4 border-emerald-600',
    textAccentClass: 'text-emerald-600',
    subtleBgClass: 'bg-emerald-50',
    headerBgClass: 'bg-emerald-600',
    cardLeftBorderClass: 'border-emerald-600',
  },
  Friday: {
    name: 'Friday',
    colorName: 'Blue',
    accentColor: '#2563eb',
    borderClass: 'border-blue-200',
    badgeClass: 'bg-blue-100 text-blue-700 border-blue-200 font-semibold',
    buttonClass: 'bg-blue-600 hover:bg-blue-700 text-white border-blue-500 shadow-sm',
    headerGlowClass: 'from-blue-600 via-blue-700 to-blue-800',
    cardAccentClass: 'border-l-4 border-blue-600',
    textAccentClass: 'text-blue-600',
    subtleBgClass: 'bg-blue-50',
    headerBgClass: 'bg-blue-600',
    cardLeftBorderClass: 'border-blue-600',
  },
  Saturday: {
    name: 'Saturday',
    colorName: 'Yellow',
    accentColor: '#d97706',
    borderClass: 'border-amber-200',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-200 font-semibold',
    buttonClass: 'bg-amber-600 hover:bg-amber-700 text-white border-amber-500 shadow-sm font-semibold',
    headerGlowClass: 'from-amber-600 via-amber-700 to-amber-800',
    cardAccentClass: 'border-l-4 border-amber-600',
    textAccentClass: 'text-amber-600',
    subtleBgClass: 'bg-amber-50',
    headerBgClass: 'bg-amber-600',
    cardLeftBorderClass: 'border-amber-600',
  },
  Sunday: {
    name: 'Sunday',
    colorName: 'Grey',
    accentColor: '#475569',
    borderClass: 'border-slate-200',
    badgeClass: 'bg-slate-200 text-slate-700 border-slate-300 font-semibold',
    buttonClass: 'bg-slate-700 hover:bg-slate-800 text-white border-slate-600 shadow-sm',
    headerGlowClass: 'from-slate-600 via-slate-700 to-slate-800',
    cardAccentClass: 'border-l-4 border-slate-600',
    textAccentClass: 'text-slate-600',
    subtleBgClass: 'bg-slate-100',
    headerBgClass: 'bg-slate-700',
    cardLeftBorderClass: 'border-slate-600',
  },
};

export function getThemeForWeekday(weekday: WeekdayName): WeekdayThemeConfig {
  return WEEKDAY_THEMES[weekday] || WEEKDAY_THEMES.Friday;
}
